# Deploy to sfgcpdfcompressor2 (Functions Premium - Windows)
name: Build and deploy PowerShell project to Azure Function App - sfgcpdfcompressor2

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'
  AZURE_FUNCTIONAPP_NAME: 'sfgcpdfcompressor2'

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          slot-name: 'Production'
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
